# Numpy <img width="100px" height="100px" src="https://pt.seaicons.com/wp-content/uploads/2015/07/Other-python-icon.png"> 

<p>O NumPy é uma biblioteca de código aberto disponível em Python que auxilia na programação matemática, 
científica, de engenharia e de ciência de dados, e nas operações de matemáticas e estatísticas.
<p> Ele foi construído para trabalhar com o: <ul><p><li>Array N-dimensional <li>Álgebra linear <li>Número aleatório <li>Transformada de Fourier</ul>

<p>Uma das grandes vantagens de usar o Numpy, além de ser bem rápido, é a eficiência de memória. Ele consegue manipular uma enorme quantidade de dados mais acessível que qualquer outra biblioteca. Além disso, o NumPy é muito conveniente para trabalhar, especialmente para multiplicação e remodelagem de matrizes.

## Como instalar o Numpy?

Antes de instalar, é importante saber que recomendamos a instalação de distribuiçoes científicas do python.
<p> As distribuições Python fornecem a própria linguagem junto com os pacotes e ferramentas mais usados. Esses arquivos que podem ser baixados exigem pouca configuração, funcionam em quase todas as configurações e fornecem todas as ferramentas científicas frequentemente usadas em Python.

<p>Listamos aqui algumas distribuições que ja tem em seu pacote de instalação a biblioteca Numpy:
<ul><b>  
<li>Anaconda/Miniconda
<li>Enthought Canotpy
<li>WinPython
<li>Pyzo
    <li>NeuroDebian repository</b>
</ul>

## Importando o Numpy


<P> Abaixo iremos ver como importamos a biblioteca NumPY, e por padrão iremos renomea-la para np.
    

In [2]:
import numpy as np

<p> Neste comando iremos verificar a a versão do Numpy.

In [88]:
print(np.__version__)## são 2 underlines

1.16.4


## Funções

Agora vamos criar uma Matriz, sempre começamos importando o Numpy. A função np.array ou numpy.array cria um array a partir de lista, tuplas ou listas de listas.

In [25]:
import numpy as np

array1d = np.array([1,2,3]) #cria uma matriz de 1 dimensão
print('Matriz de 1D')
print(array1d)

array2d = np.array([[1,2,3],[4,5,6]])#cria uma amtriz de 2 dimenções, ultilizando lista de listas
print('\nMatriz de 2D')
print(array2d)

array3d = np.array([[1,'Alline'],[2,'Ruan'],[3,'Leila']])#cria uma matriz de 3 dimensão, ultizando tuplas
print('\nMatriz 3D')
print(array3d)

Matriz de 1D
[1 2 3]

Matriz de 2D
[[1 2 3]
 [4 5 6]]

Matriz 3D
[['1' 'Alline']
 ['2' 'Ruan']
 ['3' 'Leila']]


Nesta parte iremos ver algumas funções importantes para criação de Matrizes.

<ul>
    <li><b>np.linspace(a,b,N)</b>: Cria a matriz a partir de um intervalo

In [36]:
import numpy as np

a = np.linspace(2,6,10) #cria uma matriz 1D com 10 elementos no intervalo de 2 á 6
print(a)


[2.         2.44444444 2.88888889 3.33333333 3.77777778 4.22222222
 4.66666667 5.11111111 5.55555556 6.        ]


<ul><li> <b>np.arange(a,b,N)</b>: Cria uma matriz 1D a patir de um intervalo incrementando N, seja ele um valor real.

In [38]:
import numpy as np

a = np.arange(2,6,1) #cria uma matriz 1D somando 1 no intervalo de 2 á 6 
print(a)

[2 3 4 5]


<ul><li><b>np.zeros(N)</b>: Cria uma matriz com 0's.

In [39]:
import numpy as np

a = np.zeros(10) 
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


<ul><li><b>np.ones(N,M)</b>: Cria uma matriz 2D com N linhas e M colunas de 1's.

In [46]:
import numpy as np

a = np.ones((4,5)) 
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


<ul><li><b>np.eye(N)</b>: Cria uma matriz Identidade de tamanho N.

In [44]:
import numpy as np

a = np.eye(5) 
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


<ul><li><b>.ndim</b>: nos informa a dimensão da matriz

In [2]:
import numpy as np

a = np.array([[1,2,3],[3,4,5],[3,4,5]])
print(a)

print('\nO numero de dimenções é',a.ndim)

[[1 2 3]
 [3 4 5]
 [3 4 5]]

O numero de dimenções é 2


<ul><li><b>.shape</b>: nos informa a quantidade de linha e colunas da matriz

In [53]:
import numpy as np

a = np.array([[1,2,3],[3,4,5],[3,4,5]])
print(a)

print('\nO número de linhas e colunas são',a.shape)

[[1 2 3]
 [3 4 5]
 [3 4 5]]

O numero de linhas e colunas são (3, 3)


## Operações 

Também podemos realizar operações com as matrizes, de um jeito muito simples.

<ul>
    <li><b> Soma
    <li> Subtração
    <li>Multiplicação
    <li>Divisão
    <li> Exponenciação</b>
</ul>

In [74]:
import numpy as np

m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.ones((2,3))

print('\nAs matrizes são: \n')
print('M1\n',m1)
print('\nM2\n',m2)

soma = m1+m2
sub = m1-m2
mul=m1*m2
div=m2/m1
exp= m1 ** 2

print('\nSoma\n',soma)
print('\nMultiplicação\n',mul)
print('\nDivisão\n',div)
print('\nExponencial\n',exp)


As matrizes são: 

M1
 [[1 2 3]
 [4 5 6]]

M2
 [[1. 1. 1.]
 [1. 1. 1.]]

Soma
 [[2. 3. 4.]
 [5. 6. 7.]]

Multiplicação
 [[1. 2. 3.]
 [4. 5. 6.]]

Divisão
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]

Exponencial
 [[ 1  4  9]
 [16 25 36]]


## Números Aleatórios

Existem 3 formas de gerar matrizes com números aleatórios:

<ul>
    <li><b>np.random.rand(d1,..,dn)</b>
    <li><b>np.random.randn(d1,..,dn)</b>
    <li><b>np.random.randint(n1,n2,(linha,coluna))</b>
</ul>

In [86]:
import numpy as np

 ## cria uma matriz com tamnaho que o usuario determina porem os numeros gerados pertencem ao intervalo [0,1]
a =np.random.rand(2,3)
print('\nA\n',a)

## cria uma matriz com tamnaho que o usuario determina, desta vez sem restrição
b = np.random.randn(2,3)
print('\nB\n',b)

## cria uma matriz com tamanho que o usuario determina e os numeros gerados aleatoriamente são inteiros, o usuario informa o intervalo
## neste exemplo o intervalo é de -2 a 3 com tamanho de 7 colunas e 1 linha
c = np.random.randint(-2,3,7)
print('\nC\n',c)

## neste exemplo o intervalo é de -2 a 3 com tamanho de  4 colunas e 7 linha
d = np.random.randint(-2,3,(7,4))
print('\n D\n',d)


A
 [[0.63674492 0.81918103 0.96579239]
 [0.72679309 0.63726089 0.18197615]]

B
 [[ 0.70366392 -0.12190491  0.17305901]
 [-0.22784972  0.01674753 -0.26634844]]

C
 [-1  1 -2  2 -1  0 -2]

 D
 [[-1  1  0  0]
 [-2  2 -2  2]
 [ 1 -1 -1  0]
 [ 0 -2  2 -1]
 [-1  0 -2  0]
 [-1 -1 -2 -2]
 [ 2 -2  0  2]]
